version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/" # Change if your gradle files are in a subdirectory
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "net.neoforged:*"
